import re
from datetime import datetime
def GetUomUnitSize(input):
    if input!='':
        input=input.lower()
    else:
        pass
    Unit=''
    uom=''
    size=''
    pack=''

    if re.search("((\d+|\.\d+)+(|\s+)/(|\s+)(\d+|\.\d+)+)(bg| bg|bg |rl| rl|rl |dz| dz|dz |cs|cs | cs|na|na | na|yd|yd | yd|xx| xx|xx |sf| sf|sf |ft| ft|ft |pt| pt|pt |qt| qt|qt |in| in|in |ea| ea|ea |fz| fz |fz | fz| pk|pk |pk| pk |pkg| pkg|pkg |head| head|head | sq ft| sq ft | sq ft|pack| pack|pack |l| l | l|l |g| g|g |bouquet| bouquet|bouquet |bunch| bunch|bunch |pr| pr|pr |ct| ct|ct |pint| pint|pint |lb\(avg.\)| lb \(avg.\)|lb \(avg.\) | lb \(avg.\) |fl oz|fl oz | fl oz|doz| doz|doz |quart| quart|quart |ltr| ltr|ltr |gallon| gallon|gallon |/each | /each |Each| Each|each| each|Yd.| Yd.|yd.| yd.|ml| ml|mL| mL|Ea.| ea.|ea.| ea.|Liter| Liter|liter| liter|In.| in.| In.|in.| in.|in| in|-dozenglides|-glides| glides|glide|-glide| glide|L Short|L Long|L PETITE|L Tall|yds| yds|pc|-pc|pc| Sprays|Sprays|-Sprays|Spray| Spray|-Spray|XL| XL|-XL| ROLLS|-ROLLS|ROLLS| ROLL|-ROLL|ROLL| Piece(s)|-Piece(s)|Piece(s)| piece|-piece|piece| count|-count|count|/count|lb.| lb.|lb| lb)|((\d+|\.\d+)+(|\s+)(/each | /each |Each| Each|each| each|Yd.| Yd.|yd.| yd.|ml| ml|mL| mL|Ea.| Ea.|ea.| ea.|Liter| Liter|liter| liter|lb.| lb.|lb| lb|lbs| lbs| lbs.|In.| In.|-dozenglides|-glides| glides|glide|-glide| glide|L Short|L Long|L PETITE|L Tall|yds| yds|pc|-pc|pc|Pc. Sprays|Sprays|-Sprays|Spray| Spray|-Spray|XL| XL|-XL| ROLLS|-ROLLS|ROLLS| ROLL|-ROLL|ROLL| Piece(s)|-Piece(s)|Piece(s)| piece|-piece|piece| count|-count|count|/count|oz| oz| in.|in.|In.| In.)(|\s+))|((\d+|\.\d+)+(|\s+)-(|\s+)(\d+|\.\d+)+(|\s+)(/each | /each |Each| Each|each| each|Yd.| Yd.|yd.| yd.|ml| ml|mL| mL|Ea.| Ea.|ea.| ea.|Liter| Liter|liter| liter|glides|-glides| glides|glide|-glide| glide|L Short|L Long|L PETITE|L Tall|yds| yds|pc|-pc|pc| Sprays|Sprays|-Sprays|Spray| Spray|-Spray|XL| XL|-XL| ROLLS|-ROLLS|ROLLS| ROLL|-ROLL|ROLL| Piece(s)|-Piece(s)|Piece(s)| piece|-piece|piece| count|-count|count|/count|lb. |lb.|lb| lb)(|\s+))|((\d+|\.\d+)+(|\s+)/(|\s+)(\d+|\.\d+)+(|\s+)(/each | /each |Each| Each|each| each|Yd.| Yd.|yd.| yd.|ml| ml|mL| mL|Ea.| Ea.|ea.| ea.|Liter| Liter|liter| liter|glides|-glides| glides|glide|-glide| glide|L Short|L Long|L PETITE|L Tall|yds| yds|pc|-pc|pc| Sprays|Sprays|-Sprays|Spray| Spray|-Spray|XL| XL|-XL| ROLLS|-ROLLS|ROLLS| ROLL|-ROLL|ROLL| Piece(s)|-Piece(s)|Piece(s)| piece|-piece|piece| count|-count|count|/count|Oz.| Oz.|OZ| OZ|lb. |lb.|lb| lb)(|\s+))|((\d+|\.\d+)+(|\s+)x(|\s+)(\d+|\.\d+)+(|\s+)(/each | /each |Each| Each|each| each|Yd.| Yd.|yd.| yd.|Ea.| Ea.|ea.| ea.|Liter| Liter|liter| liter|glides|-glides| glides|glide|-glide| glide|L Short|L Long|L PETITE|L Tall|yds| yds|pc|-pc|pc| Sprays|Sprays|-Sprays|Spray| Spray|-Spray|XL| XL|-XL| ROLLS|-ROLLS|ROLLS| ROLL|-ROLL|ROLL| Piece(s)|-Piece(s)|Piece(s)| piece|-piece|piece| count|-count|count|/count|in.| in.|Oz.| Oz.|OZ| OZ|lb. |lb.|lb| lb)(|\s+))",input):
        size=re.search("((\d+|\.\d+)+(|\s+)/(|\s+)(\d+|\.\d+)+)(bg| bg|bg |rl| rl|rl |dz| dz|dz |cs|cs | cs|na|na | na|yd|yd | yd|xx| xx|xx |sf| sf|sf |ft| ft|ft |pt| pt|pt |qt| qt|qt |in| in|in |ea| ea|ea |fz| fz |fz | fz| pk|pk |pk| pk |pkg| pkg|pkg |head| head|head | sq ft| sq ft | sq ft|pack| pack|pack |l| l | l|l |gallon| gallon|gallon |g| g|g |bouquet| bouquet|bouquet |bunch| bunch|bunch |pr| pr|pr |ct| ct|ct |pint| pint|pint |lb\(avg.\)| lb \(avg.\)|lb \(avg.\) | lb \(avg.\) |fl oz|fl oz | fl oz|doz| doz|doz |quart| quart|quart |ltr| ltr|ltr |/each | /each |Each| Each|each| each|Yd.| Yd.|yd.| yd.|ml| ml|mL| mL|Ea.| Ea.|ea.| ea.|Liter| Liter|liter| liter|In.| in.| In.|in.| in.|in| in|-dozenglides|-glides| glides|glide|-glide| glide|L Short|L Long|L PETITE|L Tall|yds| yds|pc|-pc|pc| Sprays|Sprays|-Sprays|Spray| Spray|-Spray|XL| XL|-XL| ROLLS|-ROLLS|ROLLS| ROLL|-ROLL|ROLL| Piece(s)|-Piece(s)|Piece(s)| piece|-piece|piece| count|-count|count|/count)|((\d+|\.\d+)+(|\s+)(/each | /each |Each| Each|each| each|Yd.| Yd.|yd.| yd.|ml| ml|mL| mL|Ea.| Ea.|ea.| ea.|Liter| Liter|liter| liter|lb| lb|lbs| lbs| lbs.|In.| In.|-dozenglides|-glides| glides|glide|-glide| glide|L Short|L Long|L PETITE|L Tall|yds| yds|pc|-pc|pc| Sprays|Sprays|-Sprays|Spray| Spray|-Spray|XL| XL|-XL| ROLLS|-ROLLS|ROLLS| ROLL|-ROLL|ROLL| Piece(s)|-Piece(s)|Piece(s)| piece|-piece|piece| count|-count|count|/count|oz| oz| in.|in.|In.| In.)(|\s+))|((\d+|\.\d+)+(|\s+)-(|\s+)(\d+|\.\d+)+(|\s+)(/each | /each |Each| Each|each| each|Yd.| Yd.|yd.| yd.|ml| ml|mL| mL|Ea.| Ea.|ea.| ea.|Liter| Liter|liter| liter|glides|-glides| glides|glide|-glide| glide|L Short|L Long|L PETITE|L Tall|yds| yds|pc|-pc|pc| Sprays|Sprays|-Sprays|Spray| Spray|-Spray|XL| XL|-XL| ROLLS|-ROLLS|ROLLS| ROLL|-ROLL|ROLL| Piece(s)|-Piece(s)|Piece(s)| piece|-piece|piece| count|-count|count|/count)(|\s+))|((\d+|\.\d+)+(|\s+)/(|\s+)(\d+|\.\d+)+(|\s+)(/each | /each |Each| Each|each| each|Yd.| Yd.|yd.| yd.|ml| ml|mL| mL|Ea.| Ea.|ea.| ea.|Liter| Liter|liter| liter|glides|-glides| glides|glide|-glide| glide|L Short|L Long|L PETITE|L Tall|yds| yds|pc|-pc|pc| Sprays|Sprays|-Sprays|Spray| Spray|-Spray|XL| XL|-XL| ROLLS|-ROLLS|ROLLS| ROLL|-ROLL|ROLL| Piece(s)|-Piece(s)|Piece(s)| piece|-piece|piece| count|-count|count|/count|Oz.| Oz.|OZ| OZ)(|\s+))|((\d+|\.\d+)+(|\s+)x(|\s+)(\d+|\.\d+)+(|\s+)(/each | /each |Each| Each|each| each|Yd.| Yd.|yd.| yd.|Ea.| Ea.|ea.| ea.|Liter| Liter|liter| liter|glides|-glides| glides|glide|-glide| glide|L Short|L Long|L PETITE|L Tall|yds| yds|pc|-pc|pc| Sprays|Sprays|-Sprays|Spray| Spray|-Spray|XL| XL|-XL| ROLLS|-ROLLS|ROLLS| ROLL|-ROLL|ROLL| Piece(s)|-Piece(s)|Piece(s)| piece|-piece|piece| count|-count|count|/count|in.| in.|Oz.| Oz.|OZ| OZ)(|\s+))",input).group()
        if size!='':
           Unit = re.search("((\d+|\.\d+)+(|\s+)/(|\s+)(\d+|\.\d+)+)|((\d+|\.\d+)+(|\s+)-(|\s+)(\d+|\.\d+)+)|((\d+|\.\d+)+(|\s+)x(|\s+)(\d+|\.\d+)+)|((\d+|\.\d+)+)|((\d+|\.\d+)+(|\s+)/(|\s+)(\d+|\.\d+)+)",size).group()
           uom = re.search("(bg| bg|bg |rl| rl|rl |dz| dz|dz |cs|cs | cs|na|na | na|yd|yd | yd|xx| xx|xx |sf| sf|sf |ft| ft|ft |pt| pt|pt |qt| qt|qt |in| in|in |ea| ea|ea |fz| fz |fz | fz| pk|pk |pk| pk |pkg| pkg|pkg |head| head|head | sq ft| sq ft | sq ft|pack| pack|pack |lb| lb | lb|lb |g| g|g |bouquet| bouquet|bouquet |bunch| bunch|bunch |pr| pr|pr |ct| ct|ct |pint| pint|pint |lb\(avg.\)| lb \(avg.\)|lb \(avg.\) | lb \(avg.\) |fl oz|fl oz | fl oz|doz| doz|doz |quart| quart|quart |ltr| ltr|ltr |gallon| gallon|gallon | /each |/each |Each| Each|each| each|Yd.| Yd.|yd.| yd.|ml| ml|mL| mL|Ea.| Ea.|ea.| ea.|Liter| Liter|liter| liter|FOz| FOz|-FOz|Cubic Inches| Cubic Inches|-Cubic Inches|cubic in| cubic in|-cubic in|Gram| Gram |-Gram|Sq. Ft.|Ffl oz|FS| FS|-FS|fs| fs|-fs|Cubic Feet| Cubic Feet|-Cubic Feet|cubic feet| cubic feet|-cubic feet|FO| FO|-FO|fo| fo|-fo|Fluid Ounce| Fluid Ounce|-Fluid Ounce|fluid ounce| fluid ounce|-fluid ounce|Ct| Ct|-Ct|ct| ct|-ct|Dozen| Dozen|-Dozen|dozen| dozen|-dozen|inches|-inches|inches| ft.|-ft.|ft.| ft|-ft|ft|-mg| mg|mg|-Inch| mm|mm| fl.oz.| fl oz|FL OZ|Fl. Oz.|OZ|Count|-Gal.|GAL|-LBS| LBS|LBS|-LB| LB|LB|ML|-QTS| QTS|QTS|GAL|-GALLON| GALLON|GALLON|GRAMS|GRM|-GM.| GM|-GM |GM |-GR |GR | GR |-liter| liter|liter|-LTR| LTR|LTR|LT|CU.IN|QT|-QT| QT|CU. IN|INCH|IN|Cu.Ft|cu ft|OUNCE|-ounce| ounce|-PINT| PINT|PINT|pound| pound|-pound|PT|QUART|SG|YD| Inch| Yard|-Yard|Yard|L | L |-L |oz| oz|in| in|.in| .in|-in|in | in|In| In|in.| in.|IN.| In.|lb.| lb.|l |l| l | l)",size).group()

    if 'lb (avg.)' in input:
        uom='lb (avg.)'
    elif 'oz (avg.)' in input:
        uom='oz (avg.)'


    if uom=="":
        if re.search("((\d+|\.\d+)+(|\s+)(bg| bg|bg |rl| rl|rl |dz| dz|dz |cs|cs | cs|na|na | na|yd|yd | yd|xx| xx|xx |sf| sf|sf |ft| ft|ft |pt| pt|pt |qt| qt|qt |in| in|in |ea| ea|ea |fz| fz |fz | fz| pk|pk |pk|pkg| pkg|pkg |head| head|head | sq ft| sq ft | sq ft|pack| pack|pack |l| l | l|l |gallon| gallon|gallon |bouquet| bouquet|bouquet |bunch| bunch|bunch |pr| pr|pr |ct| ct|ct |pint| pint|pint |lb\(avg.\)| lb \(avg.\)|lb \(avg.\) | lb \(avg.\) |fl oz|fl oz | fl oz|doz| doz|doz |quart| quart|quart |ltr| ltr|ltr |g| g|g |/each | /each |Yd.| Yd.|yd.| yd.|ml| ml|mL| mL|Ea.| Ea.|ea.| ea.|Liter| Liter|liter| liter|Each| Each|each| each| Ct.|Ct.| ct.|ct.|Lb.| Lb.|lb.| lb.| cu.ft.| sq.ft.|cu.ft.|sq.ft.| EA |EA |markers| markers|-markers|marker| marker|-marker|Meter(s)|-Meter(s)|Meter| Meter|-Meter|-Volt| Volt|mcg|-mcg| mcg|kg|-kg| kg|-G |G | G )(|\s+))|((\d+|\.\d+)+(|\s+)-(|\s+)(\d+|\.\d+)+(|\s+)(/each | /each |Yd.| Yd.|yd.| yd.|ml| ml|mL| mL|Ea.| Ea.|ea.| ea.|Liter| Liter|liter| liter|Each| Each|each| each| Ct.|Ct.| ct.|ct.|Lb.| Lb.|lb.| lb.| cu.ft.| sq.ft.|cu.ft.|sq.ft.| EA |EA |markers| markers|-markers|marker| marker|-marker|Meter(s)|-Meter(s)|Meter| Meter|-Meter|-Volt| Volt|mcg|-mcg| mcg|kg|-kg| kg|-G |G | G )(|\s+))|((\d+|\.\d+)+(|\s+)/(|\s+)(\d+|\.\d+)+(|\s+)(/each | /each |Yd.| Yd.|yd.| yd.|ml| ml|mL| mL|Ea.| Ea.|ea.| ea.|Liter| Liter|liter| liter|Each| Each|each| each| Ct.|Ct.| ct.|ct.|Lb.| Lb.|lb.| lb.| cu.ft.| sq.ft.|cu.ft.|sq.ft.| EA |EA |markers| markers|-markers|marker| marker|-marker|Meter(s)|-Meter(s)|Meter| Meter|-Meter|-Volt| Volt|mcg|-mcg| mcg|kg|-kg| kg|-G |G | G )(|\s+))|((\d+|\.\d+)+(|\s+)x(|\s+)(\d+|\.\d+)+(|\s+)(/each | /each |Yd.| Yd.|yd.| yd.|ml| ml|mL| mL|Ea.| Ea.|ea.| ea.|Liter| Liter|liter| liter|Each| Each|each| each| Ct.|Ct.| ct.|ct.|Lb.| Lb.|lb.| lb.| cu.ft.| sq.ft.|cu.ft.|sq.ft.| EA |EA |markers| markers|-markers|marker| marker|-marker|Meter(s)|-Meter(s)|Meter| Meter|-Meter|-Volt| Volt|mcg|-mcg| mcg|kg|-kg| kg|-G |G | G )(|\s+))",input):
            size=re.search("((\d+|\.\d+)+(|\s+)(bg| bg|bg |rl| rl|rl |dz| dz|dz |cs|cs | cs|na|na | na|yd|yd | yd|xx| xx|xx |sf| sf|sf |ft| ft|ft |pt| pt|pt |qt| qt|qt |in| in|in |ea| ea|ea |fz| fz |fz | fz| pk|pk |pk|pkg| pkg|pkg |head| head|head |gallon| gallon|gallon |sq ft| sq ft | sq ft|pack| pack|pack |l| l | l|l |bouquet| bouquet|bouquet |bunch| bunch|bunch |pr| pr|pr |ct| ct|ct |pint| pint|pint |lb\(avg.\)| lb \(avg.\)|lb \(avg.\) | lb \(avg.\) |fl oz|fl oz | fl oz|doz| doz|doz |quart| quart|quart |ltr| ltr|ltr |g| g|g |/each | /each |Yd.| Yd.|yd.| yd.|ml| ml|mL| mL|Ea.| Ea.|ea.| ea.|Liter| Liter|liter| liter|Each| Each|each| each| Ct.|Ct.| ct.|ct.|Lb.| Lb.|lb.| lb.| cu.ft.| sq.ft.|cu.ft.|sq.ft.| EA |EA |markers| markers|-markers|marker| marker|-marker|Meter(s)|-Meter(s)|Meter| Meter|-Meter|-Volt| Volt|mcg|-mcg| mcg|kg|-kg| kg|-G |G | G )(|\s+))|((\d+|\.\d+)+(|\s+)-(|\s+)(\d+|\.\d+)+(|\s+)(/each | /each |Yd.| Yd.|yd.| yd.|ml| ml|mL| mL|Ea.| Ea.|ea.| ea.|Liter| Liter|liter| liter|Each| Each|each| each| Ct.|Ct.| ct.|ct.|Lb.| Lb.|lb.| lb.| cu.ft.| sq.ft.|cu.ft.|sq.ft.| EA |EA |markers| markers|-markers|marker| marker|-marker|Meter(s)|-Meter(s)|Meter| Meter|-Meter|-Volt| Volt|mcg|-mcg| mcg|kg|-kg| kg|-G |G | G )(|\s+))|((\d+|\.\d+)+(|\s+)/(|\s+)(\d+|\.\d+)+(|\s+)(/each | /each |Yd.| Yd.|yd.| yd.|| ml|mL| mL|Ea.| Ea.|ea.| ea.|Liter| Liter|liter| liter|Each| Each|each| each| Ct.|Ct.| ct.|ct.|Lb.| Lb.|lb.| lb.| cu.ft.| sq.ft.|cu.ft.|sq.ft.| EA |EA |markers| markers|-markers|marker| marker|-marker|Meter(s)|-Meter(s)|Meter| Meter|-Meter|-Volt| Volt|mcg|-mcg| mcg|kg|-kg| kg|-G |G | G )(|\s+))|((\d+|\.\d+)+(|\s+)x(|\s+)(\d+|\.\d+)+(|\s+)(/each | /each |Yd.| Yd.|yd.| yd.|ml| ml|mL| mL|Ea.| Ea.|ea.| ea.|Liter| Liter|liter| liter|Each| Each|each| each| Ct.|Ct.| ct.|ct.|Lb.| Lb.|lb.| lb.| cu.ft.| sq.ft.|cu.ft.|sq.ft.| EA |EA |markers| markers|-markers|marker| marker|-marker|Meter(s)|-Meter(s)|Meter| Meter|-Meter|-Volt| Volt|mcg|-mcg| mcg|kg|-kg| kg|-G |G | G )(|\s+))",input).group()
            if size!='':
                Unit = re.search("((\d+|\.\d+)+(|\s+)/(|\s+)(\d+|\.\d+)+)|((\d+|\.\d+)+(|\s+)-(|\s+)(\d+|\.\d+)+)|((\d+|\.\d+)+(|\s+)x(|\s+)(\d+|\.\d+)+)|((\d+|\.\d+)+)",size).group()
                uom=re.search("(bg| bg|bg |rl| rl|rl |dz| dz|dz |cs|cs | cs|na|na | na|yd|yd | yd|xx| xx|xx |sf| sf|sf |ft| ft|ft |pt| pt|pt |qt| qt|qt |in| in|in |ea| ea|ea |fz| fz |fz | fz| pk|pk |pk|pkg| pkg|pkg |head| head|head | sq ft| sq ft | sq ft|pack| pack|pack |l| l | l|l |gallon| gallon|gallon |bouquet| bouquet|bouquet |bunch| bunch|bunch |pr| pr|pr |ct| ct|ct |pint| pint|pint |lb\(avg.\)| lb \(avg.\)|lb \(avg.\) | lb \(avg.\) |fl oz|fl oz | fl oz|doz| doz|doz |quart| quart|quart |ltr| ltr|ltr |g| g|g |/each | /each |Yd.| Yd.|yd.| yd.|ml| ml|mL| mL|Ea.| Ea.|ea.| ea.|Liter| Liter|liter| liter|Each| Each|each| each| Ct.|Ct.| ct.|ct.|Lb.| Lb.|lb.| lb.| cu.ft.| sq.ft.|cu.ft.|sq.ft.| EA |EA |markers| markers|-markers|marker| marker|-marker|Meter(s)|-Meter(s)|Meter| Meter|-Meter|-Volt| Volt|mcg|-mcg| mcg|kg|-kg| kg|-G |G | g |g |-g )",size).group()
    if uom == "":
        uom = re.search("(bg| bg|bg |rl| rl|rl |dz| dz|dz |cs|cs | cs|na|na | na|yd|yd | yd|xx| xx|xx |sf| sf|sf |ft| ft|ft |pt| pt|pt |qt| qt|qt |in| in|in |ea| ea|ea |fz| fz |fz | fz| pk|pk |pk|pkg| pkg|pkg |head| head|head | sq ft| sq ft | sq ft|pack| pack|pack |l| l | l|l |gallon| gallon|gallon |bouquet| bouquet|bouquet |bunch| bunch|bunch |pr| pr|pr |ct| ct|ct |pint| pint|pint |lb\(avg.\)| lb \(avg.\)|lb \(avg.\) | lb \(avg.\) |fl oz|fl oz | fl oz|doz| doz|doz |quart| quart|quart |ltr| ltr|ltr |g| g|g |/each | /each |Yd.| Yd.|yd.| yd.|ml| ml|mL| mL|Ea.| Ea.|ea.| ea.|Liter| Liter|liter| liter|Each| Each|each| each| Ct.|Ct.| ct.|ct.|Lb.| Lb.|lb.| lb.| cu.ft.| sq.ft.|cu.ft.|sq.ft.| EA |EA |markers| markers|-markers|marker| marker|-marker|Meter(s)|-Meter(s)|Meter| Meter|-Meter|-Volt| Volt|mcg|-mcg| mcg|kg|-kg| kg|-G |G | g |g |-g )",input).group()
    if Unit=='':
        Unit='1'

    if re.search("((\d+|\.\d+)+(|\s+)(pk|pk |pk| pk |pack-of|pack of - |pack of-|pack of |pack of|pack| pack|-pack|packs| packs|-packs|pk |-pk |-pk. |-pk. |Pk|Pc.| Pc.|pack of|pack|-pack)(|\s+))|((\d+|\.\d+)+(|\s+)-(|\s+)(\d+|\.\d+)+(|\s+)(pk|Pack-of|Pack of - |pack of-|pack of |pack of|pack| pack|-pack|packs| packs|-packs|pk |-pk |-pk. |-pk.|Pc.| Pc. )(|\s+))|((\d+|\.\d+)+(|\s+)/(|\s+)(\d+|\.\d+)+(|\s+)(pk|Pack-of|Pack of - |Pack of-|Pack of |Pack of|Pack| Pack|-Pack|Packs| Packs|-Packs|pk |-pk |-pk. |-pk.|Pc.| Pc. )(|\s+)|(pk|pack of|pack of |Pack of - |pack of-|pack-of-)(\d+|\.\d+)+(|\s+))",input):
        input2=re.search("((\d+|\.\d+)+(|\s+)(pk|pk |pk| pk |pack-of|pack of - |pack of-|pack of |pack of|pack| pack|-pack|packs| packs|-packs|pk |-pk |-pk. |-pk. |pk|pc.| pc.|-pack)(|\s+))|((\d+|\.\d+)+(|\s+)-(|\s+)(\d+|\.\d+)+(|\s+)(pk|pack-of|pack of - |pack of-|pack of |pack of|pack| pack|-pack|packs| packs|-packs|pk |-pk |-pk. |-pk.|Pc.| Pc. )(|\s+))|((\d+|\.\d+)+(|\s+)/(|\s+)(\d+|\.\d+)+(|\s+)(pk|Pack-of|Pack of - |Pack of-|Pack of |Pack of|Pack| Pack|-Pack|Packs| Packs|-Packs|pk |-pk |-pk. |-pk.|Pc.| Pc. )(|\s+)|(pk|pack of|pack of |Pack of - |pack of-|pack-of-)(\d+|\.\d+)+(|\s+))",input).group()
        if re.search("((\d+|\.\d+)+(|\s+)-(|\s+)(\d+|\.\d+)+)|((\d+|\.\d+)+)|((\d+|\.\d+)+(|\s+)/(|\s+)(\d+|\.\d+)+)|(\d+|\.\d+)+(|\s+)",input2):
            pack=re.search("((\d+|\.\d+)+(|\s+)-(|\s+)(\d+|\.\d+)+)|((\d+|\.\d+)+)|((\d+|\.\d+)+(|\s+)/(|\s+)(\d+|\.\d+)+)|(\d+|\.\d+)+(|\s+)",input2).group()
            if pack:
                Unit=''
                uom=''
            pass
    if pack=="":
        pack="1"

        
    #if 'gallon' in input:
    #    uom='gallon'


    #print(Unit)
    #print("uom",uom)
    #print(size)
    #print(pack)

    return [pack, uom, Unit]

#a=GetUomUnitSize('16 PK')
#print(a)


